<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Counselee extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $dummyData = [
            [
                'account_id' => 1,
                'email_add' => 'counselee1@example.com',
                'contact_number' => '123456789',
                'tel_number' => '987654321',
                'Current_address' => '123 Main St, Cityville',
                'Permanent_address' => '456 Elm St, Townsville',
                'Father_Name' => 'Albert Einstein',
                'Mother_Name' => 'Marie Curie',
                'PTC_Name' => 'Leonardo da Vinci',
                'PTC_Contact' => '555-1234',
                'Relationship_to_PTC' => 'Parent',
                'Guardian_Name' => 'Nikola Tesla',
                'Guardian_Address' => '789 Oak St, Villageton',
                'Guardian_Occupation' => 'Inventor',
                'Father_Address' => '123 Main St, Cityville',
                'Mother_Address' => '456 Elm St, Townsville',
                'Father_Contact' => '555-6789',
                'Mother_Contact' => '555-9876',
                'Father_Occupation' => 'Physicist',
                'Mother_Occupation' => 'Chemist',
                'Parents_Relation_Status' => 'Married',
                'Living_Arrangement' => 'With Parents',
                'Sibling_Rank' => 1,
            ],
            [
                'account_id' => 2,
                'email_add' => 'counselee2@example.com',
                'contact_number' => '123456789',
                'tel_number' => '987654321',
                'Current_address' => '234 Elm St, Villageton',
                'Permanent_address' => '789 Oak St, Cityville',
                'Father_Name' => 'Isaac Newton',
                'Mother_Name' => 'Ada Lovelace',
                'PTC_Name' => 'Thomas Edison',
                'PTC_Contact' => '555-5678',
                'Relationship_to_PTC' => 'Guardian',
                'Guardian_Name' => 'Galileo Galilei',
                'Guardian_Address' => '456 Pine St, Townsville',
                'Guardian_Occupation' => 'Astronomer',
                'Father_Address' => '234 Elm St, Villageton',
                'Mother_Address' => '789 Oak St, Cityville',
                'Father_Contact' => '555-2345',
                'Mother_Contact' => '555-5432',
                'Father_Occupation' => 'Physicist',
                'Mother_Occupation' => 'Mathematician',
                'Parents_Relation_Status' => 'Divorced',
                'Living_Arrangement' => 'With Mother',
                'Sibling_Rank' => 2,
            ],
            [
                'account_id' => 3,
                'email_add' => 'counselee3@example.com',
                'contact_number' => '123456789',
                'tel_number' => '987654321',
                'Current_address' => '345 Oak St, Townsville',
                'Permanent_address' => '890 Maple St, Cityville',
                'Father_Name' => 'Charles Darwin',
                'Mother_Name' => 'Rosalind Franklin',
                'PTC_Name' => 'Alexander Graham Bell',
                'PTC_Contact' => '555-3456',
                'Relationship_to_PTC' => 'Sibling',
                'Guardian_Name' => 'Ada Yonath',
                'Guardian_Address' => '567 Cedar St, Villageton',
                'Guardian_Occupation' => 'Biochemist',
                'Father_Address' => '345 Oak St, Townsville',
                'Mother_Address' => '890 Maple St, Cityville',
                'Father_Contact' => '555-6789',
                'Mother_Contact' => '555-9876',
                'Father_Occupation' => 'Naturalist',
                'Mother_Occupation' => 'Chemist',
                'Parents_Relation_Status' => 'Separated',
                'Living_Arrangement' => 'With Father',
                'Sibling_Rank' => 3,
            ],
            [
                'account_id' => 4,
                'email_add' => 'counselee4@example.com',
                'contact_number' => '123456789',
                'tel_number' => '987654321',
                'Current_address' => '456 Pine St, Villageton',
                'Permanent_address' => '901 Walnut St, Townsville',
                'Father_Name' => 'Leonhard Euler',
                'Mother_Name' => 'Emmy Noether',
                'PTC_Name' => 'Werner Heisenberg',
                'PTC_Contact' => '555-4567',
                'Relationship_to_PTC' => 'Friend',
                'Guardian_Name' => 'Marie Curie',
                'Guardian_Address' => '678 Birch St, Cityville',
                'Guardian_Occupation' => 'Physicist',
                'Father_Address' => '456 Pine St, Villageton',
                'Mother_Address' => '901 Walnut St, Townsville',
                'Father_Contact' => '555-2345',
                'Mother_Contact' => '555-5432',
                'Father_Occupation' => 'Mathematician',
                'Mother_Occupation' => 'Mathematician',
                'Parents_Relation_Status' => 'Widowed',
                'Living_Arrangement' => 'With Guardian',
                'Sibling_Rank' => 4,
            ],
            [
                'account_id' => 5,
                'email_add' => 'counselee5@example.com',
                'contact_number' => '123456789',
                'tel_number' => '987654321',
                'Current_address' => '567 Cedar St, Cityville',
                'Permanent_address' => '912 Oak St, Villageton',
                'Father_Name' => 'Aristotle',
                'Mother_Name' => 'Hypatia',
                'PTC_Name' => 'Pythagoras',
                'PTC_Contact' => '555-5678',
                'Relationship_to_PTC' => 'Relative',
                'Guardian_Name' => 'Plato',
                'Guardian_Address' => '789 Elm St, Townsville',
                'Guardian_Occupation' => 'Philosopher',
                'Father_Address' => '567 Cedar St, Cityville',
                'Mother_Address' => '912 Oak St, Villageton',
                'Father_Contact' => '555-8901',
                'Mother_Contact' => '555-1098',
                'Father_Occupation' => 'Philosopher',
                'Mother_Occupation' => 'Mathematician',
                'Parents_Relation_Status' => 'Remarried',
                'Living_Arrangement' => 'With Grandparents',
                'Sibling_Rank' => 5,
            ],
        ];
        DB::table('counselee')->insert($dummyData);
    }
}
